#include "wav.hpp"
#include <array>
#include <bit>
#include <cstring>
#include <fstream>
#include <stdexcept>
#include <string>
namespace {
template<class T> T read_le(std::istream& in){ std::array<unsigned char,sizeof(T)> b{}; in.read(reinterpret_cast<char*>(b.data()),b.size()); if(!in) throw std::runtime_error("truncated WAV"); T v{}; if constexpr(sizeof(T)==2) v=static_cast<T>(b[0]|(static_cast<unsigned>(b[1])<<8)); else if constexpr(sizeof(T)==4) v=static_cast<T>(static_cast<unsigned>(b[0])|(static_cast<unsigned>(b[1])<<8)|(static_cast<unsigned>(b[2])<<16)|(static_cast<unsigned>(b[3])<<24)); return v; }
void write_u16(std::ostream& o,std::uint16_t v){ char b[2]={static_cast<char>(v&255),static_cast<char>((v>>8)&255)};o.write(b,2);} void write_u32(std::ostream&o,std::uint32_t v){char b[4]={static_cast<char>(v&255),static_cast<char>((v>>8)&255),static_cast<char>((v>>16)&255),static_cast<char>((v>>24)&255)};o.write(b,4);} }
wav_audio read_wav(const std::filesystem::path& path){ std::ifstream in(path,std::ios::binary); if(!in) throw std::runtime_error("cannot open input WAV"); char id[4]; in.read(id,4); (void)read_le<std::uint32_t>(in); char wave[4]; in.read(wave,4); if(std::string(id,4)!="RIFF"||std::string(wave,4)!="WAVE") throw std::runtime_error("unsupported WAV container"); std::uint16_t format=0,channels=0,bits=0;std::uint32_t sr=0;std::vector<unsigned char> data; while(in){ char chunk[4];in.read(chunk,4);if(!in)break;auto size=read_le<std::uint32_t>(in);std::string name(chunk,4); if(name=="fmt "){format=read_le<std::uint16_t>(in);channels=read_le<std::uint16_t>(in);sr=read_le<std::uint32_t>(in);(void)read_le<std::uint32_t>(in);(void)read_le<std::uint16_t>(in);bits=read_le<std::uint16_t>(in); if(size>16)in.seekg(size-16,std::ios::cur);} else if(name=="data"){data.resize(size);in.read(reinterpret_cast<char*>(data.data()),size);} else in.seekg(size,std::ios::cur); if(size&1)in.seekg(1,std::ios::cur);} if(channels==0||sr==0||data.empty())throw std::runtime_error("invalid WAV"); wav_audio out{sr,channels,{}};const std::size_t bytes=bits/8;out.interleaved.resize(data.size()/bytes); if(format==1&&bits==16){for(std::size_t i=0;i<out.interleaved.size();++i){std::int16_t s=static_cast<std::int16_t>(static_cast<unsigned>(data[2*i])|(static_cast<unsigned>(data[2*i+1])<<8));out.interleaved[i]=static_cast<float>(s)/32768.0F;}} else if(format==3&&bits==32){for(std::size_t i=0;i<out.interleaved.size();++i){std::uint32_t u=static_cast<std::uint32_t>(data[4*i])|(static_cast<std::uint32_t>(data[4*i+1])<<8)|(static_cast<std::uint32_t>(data[4*i+2])<<16)|(static_cast<std::uint32_t>(data[4*i+3])<<24);out.interleaved[i]=std::bit_cast<float>(u);}} else throw std::runtime_error("only PCM16 and float32 WAV are supported"); return out; }
void write_wav_float32(const std::filesystem::path& path,const wav_audio& audio){std::ofstream out(path,std::ios::binary);if(!out)throw std::runtime_error("cannot open output WAV");const auto bytes=static_cast<std::uint32_t>(audio.interleaved.size()*4U);out.write("RIFF",4);write_u32(out,36U+bytes);out.write("WAVEfmt ",8);write_u32(out,16);write_u16(out,3);write_u16(out,audio.channels);write_u32(out,audio.sample_rate);write_u32(out,audio.sample_rate*audio.channels*4U);write_u16(out,static_cast<std::uint16_t>(audio.channels*4U));write_u16(out,32);out.write("data",4);write_u32(out,bytes);for(float value:audio.interleaved){const auto u=std::bit_cast<std::uint32_t>(value);write_u32(out,u);} }
