add_library(boiled_egg_research_host STATIC src/research_host.cpp)
target_compile_features(boiled_egg_research_host PUBLIC cxx_std_20)
target_include_directories(boiled_egg_research_host PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_link_libraries(boiled_egg_research_host PUBLIC boiled_egg_research_multires_rt)

if(BOILED_EGG_PV_RT_BUILD_TESTS)
    find_package(Threads REQUIRED)
    foreach(test host_test compact_host_test latency_bound_test host_noalloc host_threads)
        add_executable(boiled_egg_${test} tests/${test}.cpp)
        target_link_libraries(boiled_egg_${test} PRIVATE boiled_egg_research_host Threads::Threads)
        add_test(NAME boiled_egg_${test} COMMAND boiled_egg_${test})
    endforeach()
    add_executable(boiled_egg_host_c_api tests/host_c_api.c)
    target_link_libraries(boiled_egg_host_c_api PRIVATE boiled_egg_research_host)
    add_test(NAME boiled_egg_host_c_api COMMAND boiled_egg_host_c_api)
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_executable(boiled_egg_host_bench tests/host_bench.cpp)
    target_link_libraries(boiled_egg_host_bench PRIVATE boiled_egg_research_host)
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    add_executable(boiled_egg_rt_tail_probe tests/rt_tail_probe.cpp)
    target_link_libraries(boiled_egg_rt_tail_probe PRIVATE boiled_egg_research_host)
endif()
