option(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL "Build opt-in single-resolution formant preview (not promoted)" OFF)
if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL)
  target_sources(boiled_egg PRIVATE src/spectral_backend.cpp
    src/experimental/pv/pv_rt.cpp src/experimental/pv/fft.cpp)
  target_include_directories(boiled_egg PRIVATE src/experimental/pv)
  target_compile_definitions(boiled_egg PRIVATE BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL=1)
endif()
if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  # Direct same-kernel API reference, hidden from the installed ABI; not an independent acoustic oracle.
  add_library(boiled_egg_pv_oracle STATIC src/experimental/pv/pv_rt.cpp src/experimental/pv/fft.cpp)
  target_include_directories(boiled_egg_pv_oracle PUBLIC src/experimental/pv include)
  target_compile_features(boiled_egg_pv_oracle PUBLIC cxx_std_20)
  set_target_properties(boiled_egg_pv_oracle PROPERTIES CXX_VISIBILITY_PRESET hidden VISIBILITY_INLINES_HIDDEN YES)
  add_executable(boiled_egg_spectral_test tests/test_spectral_backend.cpp)
  target_link_libraries(boiled_egg_spectral_test PRIVATE boiled_egg::boiled_egg boiled_egg_pv_oracle)
  add_test(NAME boiled_egg_spectral_test COMMAND boiled_egg_spectral_test)
endif()
if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  foreach(name noalloc threads)
    add_executable(boiled_egg_spectral_${name}_test tests/test_spectral_${name}.cpp)
    target_link_libraries(boiled_egg_spectral_${name}_test PRIVATE boiled_egg::boiled_egg Threads::Threads)
    add_test(NAME boiled_egg_spectral_${name}_test COMMAND boiled_egg_spectral_${name}_test)
  endforeach()
endif()

if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  add_executable(boiled_egg_spectral_boundaries_test tests/test_spectral_boundaries.cpp)
  target_link_libraries(boiled_egg_spectral_boundaries_test PRIVATE boiled_egg::boiled_egg)
  add_test(NAME boiled_egg_spectral_boundaries_test COMMAND boiled_egg_spectral_boundaries_test)
endif()

if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS AND BOILED_EGG_BUILD_TOOLS)
  add_executable(boiled_egg_pv_oracle_cli tests/pv_oracle_cli.cpp tools/wav_io.cpp)
  target_include_directories(boiled_egg_pv_oracle_cli PRIVATE tools)
  target_link_libraries(boiled_egg_pv_oracle_cli PRIVATE boiled_egg_pv_oracle)
endif()

if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  add_executable(boiled_egg_dynamic_pitch_test tests/test_dynamic_pitch.cpp)
  target_link_libraries(boiled_egg_dynamic_pitch_test PRIVATE boiled_egg::boiled_egg)
  add_test(NAME boiled_egg_dynamic_pitch_test COMMAND boiled_egg_dynamic_pitch_test)
endif()
if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_BENCH AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  add_executable(boiled_egg_dynamic_pitch_bench quality/dynamic_pitch/bench.cpp)
  target_link_libraries(boiled_egg_dynamic_pitch_bench PRIVATE boiled_egg::boiled_egg)
endif()
if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  add_executable(boiled_egg_time_ramps_test tests/test_time_ramps.cpp)
  target_link_libraries(boiled_egg_time_ramps_test PRIVATE boiled_egg::boiled_egg)
  add_test(NAME boiled_egg_time_ramps_test COMMAND boiled_egg_time_ramps_test)
endif()

if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  add_executable(boiled_egg_ramp_noalloc_test tests/test_ramp_noalloc.cpp)
  target_link_libraries(boiled_egg_ramp_noalloc_test PRIVATE boiled_egg::boiled_egg)
  add_test(NAME boiled_egg_ramp_noalloc_test COMMAND boiled_egg_ramp_noalloc_test)
endif()

if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_TESTS)
  foreach(name rounding threads)
    add_executable(boiled_egg_ramp_${name}_test quality/automation_ramps/test_${name}.cpp)
    target_link_libraries(boiled_egg_ramp_${name}_test PRIVATE boiled_egg::boiled_egg Threads::Threads)
    add_test(NAME boiled_egg_ramp_${name}_test COMMAND boiled_egg_ramp_${name}_test)
  endforeach()
endif()
if(BOILED_EGG_ENABLE_EXPERIMENTAL_SPECTRAL AND BOILED_EGG_BUILD_BENCH AND CMAKE_SYSTEM_NAME STREQUAL "Linux")
  add_executable(boiled_egg_explicit_ramp_bench quality/automation_ramps/bench.cpp)
  target_link_libraries(boiled_egg_explicit_ramp_bench PRIVATE boiled_egg::boiled_egg)
endif()
